In [1]:
import pandas as pd
from pathlib import Path

In [2]:
crime_df = pd.read_csv(Path("../cleaned_data_2015_2018/all_data_merged_cleaned_2015_2018.csv"))
crime_df

event_unique_id     crime  occ_year occ_month  occ_day   occ_dow  \
0          GO-20155154   assault      2015   January        1  Thursday   
1          GO-20151233   assault      2015   January        1  Thursday   
2           GO-2015862   assault      2015   January        1  Thursday   
3           GO-2015182   assault      2015   January        1  Thursday   
4           GO-2015276   assault      2015   January        1  Thursday   
...                ...       ...       ...       ...      ...       ...   
166507  GO-20181887731  homicide      2018   October       12    Friday   
166508  GO-20181923388  homicide      2018   October       18  Thursday   
166509  GO-20181939006  homicide      2018   October       20  Saturday   
166510  GO-20182113063  homicide      2018  November       16    Friday   
166511  GO-20182242344  homicide      2018  December        6  Thursday   

        occ_hour premises_type hood_140  \
0             23         House      115   
1              3    Commercial       77   
2              2    Commercial       77   
3              0    Commercial        1   
4              0       Outside       77   
...          ...           ...      ...   
166507         0           NaN       75   
166508         0           NaN      120   
166509         0           NaN      124   
166510         0           NaN       73   
166511         0           NaN       73   

                             neighbourhood_140  long_wgs84  lat_wgs84  \
0                           Mount Dennis (115)  -79.504668  43.693238   
1       Waterfront Communities-The Island (77)  -79.392855  43.647315   
2       Waterfront Communities-The Island (77)  -79.387700  43.649776   
3                   West Humber-Clairville (1)  -79.595562  43.686751   
4       Waterfront Communities-The Island (77)  -79.400096  43.645835   
...                                        ...         ...        ...   
166507              Church-Yonge Corridor (75)  -79.376699  43.656958   
166508               Clairlea-Birchmount (120)  -79.286292  43.699070   
166509                      Kennedy Park (124)  -79.264551  43.732765   
166510                          Moss Park (73)  -79.369005  43.654614   
166511                          Moss Park (73)  -79.374451  43.660196   

              date  
0       2015-01-01  
1       2015-01-01  
2       2015-01-01  
3       2015-01-01  
4       2015-01-01  
...            ...  
166507  2018-10-12  
166508  2018-10-18  
166509  2018-10-20  
166510  2018-11-16  
166511  2018-12-06  

[166512 rows x 13 columns]

In [3]:
daily_crime = crime_df.groupby(by=['date', "occ_dow"])["crime"].value_counts().unstack(fill_value=0)
daily_crime

crime                assault  auto_theft  bicycle_theft  break_and_enter  \
date       occ_dow                                                         
2015-01-01 Thursday      158           7              5               21   
2015-01-02 Friday         34           9              4               18   
2015-01-03 Saturday       37          10              0                4   
2015-01-04 Sunday         44           5              1               11   
2015-01-05 Monday         39           6              1               24   
...                      ...         ...            ...              ...   
2018-12-27 Thursday       38           7              2               21   
2018-12-28 Friday         35          13              2               21   
2018-12-29 Saturday       37          10              3               26   
2018-12-30 Sunday         43           8              3               22   
2018-12-31 Monday         38          14              2               20   

crime                homicide  robbery  shooting  theft_from_motor_vehicle  \
date       occ_dow                                                           
2015-01-01 Thursday         0        8         0                        34   
2015-01-02 Friday           0        6         0                        34   
2015-01-03 Saturday         0        8         0                        21   
2015-01-04 Sunday           0        5         0                        33   
2015-01-05 Monday           0        5         1                        31   
...                       ...      ...       ...                       ...   
2018-12-27 Thursday         0        7         0                        30   
2018-12-28 Friday           0       12         0                        31   
2018-12-29 Saturday         0        7         0                        21   
2018-12-30 Sunday           0        7         0                        22   
2018-12-31 Monday           0       11         0                        23   

crime                theft_over  
date       occ_dow               
2015-01-01 Thursday           5  
2015-01-02 Friday             2  
2015-01-03 Saturday           3  
2015-01-04 Sunday             1  
2015-01-05 Monday             2  
...                         ...  
2018-12-27 Thursday           1  
2018-12-28 Friday             1  
2018-12-29 Saturday           4  
2018-12-30 Sunday             3  
2018-12-31 Monday             4  

[1461 rows x 9 columns]

In [4]:
daily_crime.columns

Index(['assault', 'auto_theft', 'bicycle_theft', 'break_and_enter', 'homicide',
       'robbery', 'shooting', 'theft_from_motor_vehicle', 'theft_over'],
      dtype='object', name='crime')

In [5]:
target_columns = [f'{column}_count' for column in daily_crime.columns]

daily_crime.columns = target_columns
daily_crime

assault_count  auto_theft_count  bicycle_theft_count  \
date       occ_dow                                                          
2015-01-01 Thursday            158                 7                    5   
2015-01-02 Friday               34                 9                    4   
2015-01-03 Saturday             37                10                    0   
2015-01-04 Sunday               44                 5                    1   
2015-01-05 Monday               39                 6                    1   
...                            ...               ...                  ...   
2018-12-27 Thursday             38                 7                    2   
2018-12-28 Friday               35                13                    2   
2018-12-29 Saturday             37                10                    3   
2018-12-30 Sunday               43                 8                    3   
2018-12-31 Monday               38                14                    2   

                     break_and_enter_count  homicide_count  robbery_count  \
date       occ_dow                                                          
2015-01-01 Thursday                     21               0              8   
2015-01-02 Friday                       18               0              6   
2015-01-03 Saturday                      4               0              8   
2015-01-04 Sunday                       11               0              5   
2015-01-05 Monday                       24               0              5   
...                                    ...             ...            ...   
2018-12-27 Thursday                     21               0              7   
2018-12-28 Friday                       21               0             12   
2018-12-29 Saturday                     26               0              7   
2018-12-30 Sunday                       22               0              7   
2018-12-31 Monday                       20               0             11   

                     shooting_count  theft_from_motor_vehicle_count  \
date       occ_dow                                                    
2015-01-01 Thursday               0                              34   
2015-01-02 Friday                 0                              34   
2015-01-03 Saturday               0                              21   
2015-01-04 Sunday                 0                              33   
2015-01-05 Monday                 1                              31   
...                             ...                             ...   
2018-12-27 Thursday               0                              30   
2018-12-28 Friday                 0                              31   
2018-12-29 Saturday               0                              21   
2018-12-30 Sunday                 0                              22   
2018-12-31 Monday                 0                              23   

                     theft_over_count  
date       occ_dow                     
2015-01-01 Thursday                 5  
2015-01-02 Friday                   2  
2015-01-03 Saturday                 3  
2015-01-04 Sunday                   1  
2015-01-05 Monday                   2  
...                               ...  
2018-12-27 Thursday                 1  
2018-12-28 Friday                   1  
2018-12-29 Saturday                 4  
2018-12-30 Sunday                   3  
2018-12-31 Monday                   4  

[1461 rows x 9 columns]

In [6]:
daily_crime.reset_index()

date   occ_dow  assault_count  auto_theft_count  \
0     2015-01-01  Thursday            158                 7   
1     2015-01-02    Friday             34                 9   
2     2015-01-03  Saturday             37                10   
3     2015-01-04    Sunday             44                 5   
4     2015-01-05    Monday             39                 6   
...          ...       ...            ...               ...   
1456  2018-12-27  Thursday             38                 7   
1457  2018-12-28    Friday             35                13   
1458  2018-12-29  Saturday             37                10   
1459  2018-12-30    Sunday             43                 8   
1460  2018-12-31    Monday             38                14   

      bicycle_theft_count  break_and_enter_count  homicide_count  \
0                       5                     21               0   
1                       4                     18               0   
2                       0                      4               0   
3                       1                     11               0   
4                       1                     24               0   
...                   ...                    ...             ...   
1456                    2                     21               0   
1457                    2                     21               0   
1458                    3                     26               0   
1459                    3                     22               0   
1460                    2                     20               0   

      robbery_count  shooting_count  theft_from_motor_vehicle_count  \
0                 8               0                              34   
1                 6               0                              34   
2                 8               0                              21   
3                 5               0                              33   
4                 5               1                              31   
...             ...             ...                             ...   
1456              7               0                              30   
1457             12               0                              31   
1458              7               0                              21   
1459              7               0                              22   
1460             11               0                              23   

      theft_over_count  
0                    5  
1                    2  
2                    3  
3                    1  
4                    2  
...                ...  
1456                 1  
1457                 1  
1458                 4  
1459                 3  
1460                 4  

[1461 rows x 11 columns]

In [7]:
daily_weather_df = pd.read_csv(Path('../cleaned_data_2015_2018/toronto_daily_weather_2015_2018.csv'))
daily_weather_df

date  max_temperature  min_temperature  max_relative_humidity  \
0     2018-12-31              5.0             -2.5                     94   
1     2018-12-30              0.7             -6.6                     88   
2     2018-12-29              2.7             -7.0                     80   
3     2018-12-28             12.4              2.7                     95   
4     2018-12-27              2.8             -7.4                     87   
...          ...              ...              ...                    ...   
1456  2015-01-05             -5.8            -14.4                     83   
1457  2015-01-04              4.3             -5.9                     98   
1458  2015-01-03              1.5             -5.8                     97   
1459  2015-01-02             -1.0             -6.1                     83   
1460  2015-01-01             -1.9             -8.1                     69   

      avg_relative_humidity  avg_pressure_sea  max_wind_speed  precipitation  \
0                      79.5            100.78              21           13.6   
1                      78.0            102.03              24            1.2   
2                      68.0            101.86              34            0.0   
3                      84.5            100.89              30            1.8   
4                      74.0            102.52              30            5.4   
...                     ...               ...             ...            ...   
1456                   69.5            102.38              45            0.8   
1457                   82.5            100.69              43            6.8   
1458                   82.5            101.96              29           10.8   
1459                   66.0            102.30              36            0.6   
1460                   60.0            101.27              36            0.0   

      rain  snow  snow_on_ground  daylight  avg_cloud_cover_8  
0     13.6   0.0             0.0      8.98                4.5  
1      0.0   1.6             2.0      8.97                5.0  
2      0.0   0.0             0.0      8.95                4.5  
3      1.8   0.0             0.0      8.93                4.5  
4      5.4   0.0             0.0      8.93                4.0  
...    ...   ...             ...       ...                ...  
1456   0.0   0.8             1.0      9.05                3.5  
1457   6.4   0.4             0.0      9.02                6.0  
1458   8.0   2.4             0.0      9.00                5.0  
1459   0.0   0.4             0.0      9.00                6.0  
1460   0.0   0.0             0.0      9.00                4.5  

[1461 rows x 13 columns]

In [8]:
crime_weather_df = daily_weather_df.merge(daily_crime, how="left", on="date")
crime_weather_df

date  max_temperature  min_temperature  max_relative_humidity  \
0     2018-12-31              5.0             -2.5                     94   
1     2018-12-30              0.7             -6.6                     88   
2     2018-12-29              2.7             -7.0                     80   
3     2018-12-28             12.4              2.7                     95   
4     2018-12-27              2.8             -7.4                     87   
...          ...              ...              ...                    ...   
1456  2015-01-05             -5.8            -14.4                     83   
1457  2015-01-04              4.3             -5.9                     98   
1458  2015-01-03              1.5             -5.8                     97   
1459  2015-01-02             -1.0             -6.1                     83   
1460  2015-01-01             -1.9             -8.1                     69   

      avg_relative_humidity  avg_pressure_sea  max_wind_speed  precipitation  \
0                      79.5            100.78              21           13.6   
1                      78.0            102.03              24            1.2   
2                      68.0            101.86              34            0.0   
3                      84.5            100.89              30            1.8   
4                      74.0            102.52              30            5.4   
...                     ...               ...             ...            ...   
1456                   69.5            102.38              45            0.8   
1457                   82.5            100.69              43            6.8   
1458                   82.5            101.96              29           10.8   
1459                   66.0            102.30              36            0.6   
1460                   60.0            101.27              36            0.0   

      rain  snow  ...  avg_cloud_cover_8  assault_count  auto_theft_count  \
0     13.6   0.0  ...                4.5             38                14   
1      0.0   1.6  ...                5.0             43                 8   
2      0.0   0.0  ...                4.5             37                10   
3      1.8   0.0  ...                4.5             35                13   
4      5.4   0.0  ...                4.0             38                 7   
...    ...   ...  ...                ...            ...               ...   
1456   0.0   0.8  ...                3.5             39                 6   
1457   6.4   0.4  ...                6.0             44                 5   
1458   8.0   2.4  ...                5.0             37                10   
1459   0.0   0.4  ...                6.0             34                 9   
1460   0.0   0.0  ...                4.5            158                 7   

      bicycle_theft_count  break_and_enter_count  homicide_count  \
0                       2                     20               0   
1                       3                     22               0   
2                       3                     26               0   
3                       2                     21               0   
4                       2                     21               0   
...                   ...                    ...             ...   
1456                    1                     24               0   
1457                    1                     11               0   
1458                    0                      4               0   
1459                    4                     18               0   
1460                    5                     21               0   

      robbery_count  shooting_count  theft_from_motor_vehicle_count  \
0                11               0                              23   
1                 7               0                              22   
2                 7               0                              21   
3                12               0                              31   
4                 7          

In [25]:
# Split the data into input and output variables
output_count = len(target_columns)

X = crime_weather_df.iloc[:, :-output_count].drop("date", axis=1).values
y = [crime_weather_df[target].values for target in target_columns]

assert X.shape[0] == y[0].shape[0], "Number of samples in X and y do not match"

In [26]:
print(X.shape)
for target in y:
    print(target.shape)

(1461, 12)
(1461,)
(1461,)
(1461,)
(1461,)
(1461,)
(1461,)
(1461,)
(1461,)
(1461,)


In [27]:
y

[array([ 38,  43,  37, ...,  37,  34, 158], dtype=int64),
 array([14,  8, 10, ..., 10,  9,  7], dtype=int64),
 array([2, 3, 3, ..., 0, 4, 5], dtype=int64),
 array([20, 22, 26, ...,  4, 18, 21], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([11,  7,  7, ...,  8,  6,  8], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([23, 22, 21, ..., 21, 34, 34], dtype=int64),
 array([4, 3, 4, ..., 3, 2, 5], dtype=int64)]

In [29]:
import numpy as np
y_stacked = np.column_stack(y)
y_stacked

array([[ 38,  14,   2, ...,   0,  23,   4],
       [ 43,   8,   3, ...,   0,  22,   3],
       [ 37,  10,   3, ...,   0,  21,   4],
       ...,
       [ 37,  10,   0, ...,   0,  21,   3],
       [ 34,   9,   4, ...,   0,  34,   2],
       [158,   7,   5, ...,   0,  34,   5]], dtype=int64)

In [43]:
# WINNER method to unstack

y_unstack = np.array_split(y_stacked, y_stacked.shape[0])
y_unstack

[array([[38, 14,  2, 20,  0, 11,  0, 23,  4]], dtype=int64),
 array([[43,  8,  3, 22,  0,  7,  0, 22,  3]], dtype=int64),
 array([[37, 10,  3, 26,  0,  7,  0, 21,  4]], dtype=int64),
 array([[35, 13,  2, 21,  0, 12,  0, 31,  1]], dtype=int64),
 array([[38,  7,  2, 21,  0,  7,  0, 30,  1]], dtype=int64),
 array([[39,  9,  1, 22,  0, 10,  0, 24,  1]], dtype=int64),
 array([[49,  3,  2, 25,  0,  3,  1, 18,  1]], dtype=int64),
 array([[39, 11,  6, 23,  0,  8,  1, 22,  2]], dtype=int64),
 array([[48, 15,  3, 24,  0,  6,  0, 25,  3]], dtype=int64),
 array([[39,  7,  4, 29,  0,  9,  0, 25,  4]], dtype=int64),
 array([[38, 14,  1, 27,  0,  8,  0, 18,  2]], dtype=int64),
 array([[42, 18,  7, 24,  0,  7,  0, 22,  3]], dtype=int64),
 array([[36, 16,  4, 19,  0, 10,  2, 22,  1]], dtype=int64),
 array([[45, 10,  6, 27,  0,  7,  1, 17,  5]], dtype=int64),
 array([[46, 16,  3, 19,  0,  8,  0, 23,  3]], dtype=int64),
 array([[43, 16,  1, 24,  0,  9,  0, 22,  3]], dtype=int64),
 array([[41, 16,  2, 25,

In [11]:
# Split data into train and test data
from sklearn.model_selection import train_test_split

# Stack the outputs (y) to make the shape match the features (X)
import numpy as np
y_stacked = np.column_stack(y)

X_train, X_test, y_train, y_test = train_test_split(X, y_stacked, random_state=0)

assert X_train.shape[0] == y_train.shape[0], "Number of samples in X_train and y_train do not match"
assert X_test.shape[0] == y_test.shape[0], "Number of samples in X_test and y_test do not match"

In [12]:
# Standardize the data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaler = scaler.fit(X_train)

X_train_scaled = X_scaler.fit_transform(X_train)
X_test_scaled = X_scaler.fit_transform(X_test)

In [14]:
y_train.shape

(1095, 9)

In [44]:
# Unstack the y data again

y_train_list = np.array_split(y_train, y_train.shape[0])
y_test_list = np.array_split(y_test, y_test.shape[0])

[array([[47, 11,  5, 11,  0,  3,  0, 33,  3]], dtype=int64),
 array([[53,  9, 14, 23,  0,  6,  0, 18,  3]], dtype=int64),
 array([[30,  2,  0, 12,  0,  5,  0, 29,  0]], dtype=int64),
 array([[33,  6, 10, 11,  0, 12,  0, 20,  4]], dtype=int64),
 array([[45,  8, 10, 30,  0,  8,  0, 20,  3]], dtype=int64),
 array([[42, 14, 11, 27,  0,  6,  0, 29,  2]], dtype=int64),
 array([[44,  4, 14, 12,  0,  5,  0, 29,  2]], dtype=int64),
 array([[47,  3,  4, 16,  0, 11,  0, 29,  1]], dtype=int64),
 array([[46, 10,  5, 17,  0,  9,  0, 20,  6]], dtype=int64),
 array([[36,  7, 19, 25,  0, 11,  0, 25,  5]], dtype=int64),
 array([[30,  6,  3, 22,  0, 10,  0, 17,  1]], dtype=int64),
 array([[28, 13,  0, 10,  0,  5,  0, 19,  0]], dtype=int64),
 array([[34, 10, 22, 16,  0, 12,  0, 25,  3]], dtype=int64),
 array([[39, 14, 13, 12,  0,  7,  0, 32,  3]], dtype=int64),
 array([[41,  4, 17, 15,  0,  6,  0, 28,  1]], dtype=int64),
 array([[46, 13, 13, 26,  0,  5,  0, 31,  1]], dtype=int64),
 array([[38,  5,  1,  5,

In [45]:
import tensorflow as tf

# Define the input shape. Equal to the amount of feature columns (Total column count - output count - removed date column)
input_shape = (len(crime_weather_df.columns) - output_count - 1, )

# Define the input layer
inputs = tf.keras.Input(shape=input_shape)

# Define the hidden layers
hidden1 = tf.keras.layers.Dense(32, activation='relu')(inputs)
hidden2 = tf.keras.layers.Dense(16, activation='relu')(hidden1)

# Define the output layers
output_layers=[]

for target_col in target_columns:
    output_layers.append(tf.keras.layers.Dense(1, activation="linear", name=target_col)(hidden2))

# Define the model
model = tf.keras.Model(inputs=inputs, outputs=output_layers)

# Compile the model
model.compile(optimizer='adam', loss='mse')

In [49]:
# Fit the model
model.fit(X_train_scaled, y_train, epochs=50, batch_size=32)

Epoch 1/50
35/35 [==============================] - 2s 1ms/step - loss: 3270.1797 - assault_count_loss: 355.9417 - auto_theft_count_loss: 366.8662 - bicycle_theft_count_loss: 357.8276 - break_and_enter_count_loss: 366.3675 - homicide_count_loss: 363.7544 - robbery_count_loss: 371.2000 - shooting_count_loss: 374.4594 - theft_from_motor_vehicle_count_loss: 358.3065 - theft_over_count_loss: 355.4566
Epoch 2/50
35/35 [==============================] - 0s 1ms/step - loss: 3117.2856 - assault_count_loss: 352.3089 - auto_theft_count_loss: 336.3059 - bicycle_theft_count_loss: 337.2585 - break_and_enter_count_loss: 348.6637 - homicide_count_loss: 351.1876 - robbery_count_loss: 359.4713 - shooting_count_loss: 360.6938 - theft_from_motor_vehicle_count_loss: 333.5748 - theft_over_count_loss: 337.8205
Epoch 3/50
35/35 [==============================] - 0s 1ms/step - loss: 2822.3535 - assault_count_loss: 329.1219 - auto_theft_count_loss: 296.0532 - bicycle_theft_count_loss: 304.1938 - break_and_ente

In [52]:
# Evaluate the model on test data
loss, accuracy = model.evaluate(X_test_scaled, y_test)

# Print the results
print(loss)
print('Test accuracy:', *accuracy)

12/12 [==============================] - 0s 1ms/step - loss: 1955.8759 - assault_count_loss: 217.2271 - auto_theft_count_loss: 217.4003 - bicycle_theft_count_loss: 217.3927 - break_and_enter_count_loss: 217.3403 - homicide_count_loss: 217.4127 - robbery_count_loss: 217.3475 - shooting_count_loss: 217.2379 - theft_from_motor_vehicle_count_loss: 217.2639 - theft_over_count_loss: 217.2534


ValueError: too many values to unpack (expected 2)